### ISSUE TITLE
Broken gif

### ISSUE THREAD

**Issue by earthctzn** [learn-co-curriculum/react-dynamic-components#1]
Hello,

It looks like there is a broken gif in this lab that is not displaying. 
![Screen Shot 2020-01-15 at 8 17 58 PM](https://user-images.githubusercontent.com/48991697/72485013-5660cb80-37d4-11ea-85e6-7fb446e15d4c.png)

**Comment by reneenordholm** [comment]
I (and a few other people in  my cohort) also could not see the image.

**Comment by maxwellbenton** [comment]
Hi @earthctzn and @reneenordholm,

Thank you for this feedback. We've updated this lesson and confirmed that the GIF should now display in Learn, which should resolve this issue.

Thank you for contributing to a Learn lesson!
